
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chat_hotwire_development
  username: postgres
  password: 159753

test:
  <<: *default
  database: chat_hotwire_test
  username: postgres

  password: 159753

production:
  <<: *default
  database: chat_hotwire_production
  username: postgres
  password: 159753
